import{a as f,i as c,S as L}from"./assets/vendor-hwdYKDic.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const p of t.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const m=s=>`
       
            <li class='gallery-card'>
                <a class='gallery-link' href='${s.largeImageURL}'>
                    <img class='gallery-img' src='${s.webformatURL}' alt='${s.tags}' />
                    <div class='img-card'>
                        <span class='span-text'>Likes <span class='span-number'>${s.likes}</span></span>
                        <span class='span-text'>Views <span class='span-number'>${s.views}</span></span>
                        <span class='span-text'>Comments <span class='span-number'>${s.comments}</span></span>
                        <span class='span-text'>Downloads <span class='span-number'>${s.downloads}</span></span>
                    </div>
                </a>
            </li>`,y=(s,r)=>{const a={params:{key:"48454112-2bb14e2eb4c862c9f6d932a5d",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15",page:r}};return f.get("https://pixabay.com/api/",a)},g=document.querySelector(".js-search-form"),o=document.querySelector(".js-gallery"),u=document.querySelector(".loader"),l=document.querySelector(".load-more-btn");let i=1,d="";const b=async s=>{try{if(s.preventDefault(),d=s.currentTarget.elements.text_q.value.trim(),d===""){c.warning({title:"Caution",message:"Please, enter valid search requirements!"});return}i=1,l.classList.add("is-hidden"),u.style.display="block",o.innerHTML="";const{data:r}=await y(d,i);if(r.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!"}),o.innerHTML="",g.reset(),u.style.display="none";return}r.totalHits>15&&(l.classList.remove("is-hidden"),l.addEventListener("click",h));const a=r.hits.map(e=>m(e)).join("");o.innerHTML=a;const n=new L(".gallery-card a.gallery-link  ",{});console.log(n)}catch(r){o.innerHTML===""&&(console.err("Error fetching data:",r),c.err({title:"Error",message:"An error occurred while searching for images"}))}u.style.display="none"};g.addEventListener("submit",b);const h=async s=>{try{i++;const{data:r}=await y(d,i),a=r.hits.map(n=>m(n)).join("");o.insertAdjacentHTML("beforeend",a),i*15>=r.totalHits&&(c.error({message:"We're sorry, but you've reached the end of search results."}),l.classList.add("is-hidden"),l.removeEventListener("click",h))}catch(r){console.log(r)}};
//# sourceMappingURL=index.js.map
